### ISSUE TITLE
Can we use VL-BERT as image or text generator?

### ISSUE THREAD

**Issue by xealml** [jackroos/VL-BERT#12]
use VL-Bert as a generator for text or image or both?

**Comment by jackroos** [comment]
Yeah, this is an interesting topic. Theoretically, VL-BERT can be used as image/text generator since it models joint distribution of image RoIs and text tokens (e.g., [this paper](https://arxiv.org/pdf/1902.04094.pdf) is a method to use BERT for text generation). But pre-training tasks of VL-BERT is not designed for generation task, so other pre-training tasks may be needed to obtain good results. Thanks!

**Comment by xealml** [comment]
Thanks for your reply.
